const Router = require('express')
const router = new Router()
const OrdersRouter = require('./OrdersRouter')
const ProductsRouter = require('./ProductsRouter')
const TrashesRouter = require('./TrashesRouter')
const ReviewsRouter = require('./ReviewsRouter')
const UsersRouter = require('./UserRouter')
const AnimalsRouter = require('./AnimalsRouter')
const CategoriesRouter = require('./CategoriesRouter')
router.use('/Orders', OrdersRouter)
router.use('/User', UsersRouter)
router.use('/Trashes', TrashesRouter)
router.use('/Reviews', ReviewsRouter)
router.use('/Products', ProductsRouter)
router.use('/Animals', AnimalsRouter)
router.use('/Categories', CategoriesRouter)
module.exports=router